# 第62题：【Promise】下面代码的输出

```js
const p1 = new Promise((resolve) => {
  setTimeout(() => {
    resolve('resolve3');
    console.log('timer1')
  }, 0)
  resolve('resovle1');
  resolve('resolve2');
}).then(res => {
  console.log(res)
  setTimeout(() => {
    console.log(p1)
  }, 1000)
}).finally(res => {
  console.log('finally', res)
})
```

## 解析

* `Promise`的状态一旦改变就无法改变

* `finally`不管`Promise`的状态是`resolved`还是`rejected`都会执行，且它的回调函数是接收不到`Promise`的结果的，所以`finally()`中的`res`是一个迷惑项。

* 最后一个定时器打印出的p1其实是`.finally`的返回值，我们知道`.finally`的返回值如果在没有抛出错误的情况下默认会是上一个`Promise`的返回值，而这道题中`.finally`上一个`Promise`是`.then()`，但是这个`.then()`并没有返回值，所以p1打印出来的`Promise`的值会是`undefined`，如果你在定时器的下面加上一个`return 1`，则值就会变成1。

## 结果

```
'resolve1'
'finally' undefined
'timer1'
Promise{<resolved>: undefined}
```