# 第65题：【Promise】下面代码的输出

```js
async function async1 () {
  try {
    await Promise.reject('error!!!')
  } catch(e) {
    console.log(e)
  }
  console.log('async1');
  return Promise.resolve('async1 success')
}
async1().then(res => console.log(res))
console.log('script start')
```

## 参考

```
'script start'
'error!!!'
'async1'
'async1 success'
```