# 第66题：【Promise】下面代码的输出

```js
async function async1 () {
  await async2();
  console.log('async1');
  return 'async1 success'
}
async function async2 () {
  return new Promise((resolve, reject) => {
    console.log('async2')
    reject('error')
  })
}
async1().then(res => console.log(res))
```

## 参考

```
'async2'
Uncaught (in promise) error
```